config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  mount TalkingStick::Engine, at: '/talking_stick'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :tests
  resources :questions
  resources :answers,             only: [:create, :destroy]
  resources :results

  post '/talking_stick/rooms/:id', to: 'talking_stick/rooms#img_board'
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/result.rb
class Result < ActiveRecord::Base
  serialize :results, Array
  belongs_to :user
  belongs_to :test
  default_scope { order('results.created_at DESC') }
  validates :user_id, presence: true
  validates :test_id, presence: true
  validates_numericality_of :attempt_count, :pass_time
  validates_uniqueness_of :test_id, scope: :user_id, message: "уже был пройден Вами ранее!"
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  def show
    @result = Result.find(params[:id])
    @test = @result.test
    @questions = @test.questions
    @right_answers_count = right_answer_count(@questions, @result)
    @percent = percent(@test, @result)
  end

  def new
    @test = Test.find(params[:id])
    @users = User.where(activated: true).all
    @result = Result.new
  end

  def create
    @test = Test.find(params[:id])
    @users = User.where(activated: true).all
    @result = Result.new
    $error = false
    if params[:users] == NIL
      $error = true
      flash[:danger] = "Вы не назначили тест ни одному пользователю"
      render 'new'
    else
      users = params[:users].to_unsafe_hash.map{ |key, value| key if value == "checked"}
      users.each do |user_id|
        @result = Result.new(user_id: user_id.to_i,
                       test_id: params[:id],
                       attempt_count: params[:attempt_count][user_id].to_i,
                       pass_time: params[:pass_time][user_id].to_i * 60)
        unless @result.save
          @result = Result.find_by(user_id: user_id.to_i, test_id: params[:id])
          unless @result && @result.update_attributes(attempt_count: params[:attempt_count][user_id].to_i,
                                    pass_time: params[:pass_time][user_id].to_i * 60)
            $error = true
            flash[:danger] = "Что-то пошло не так. Попробуйте еще раз."
          end
        end
      end
      if $error
        redirect_to new_result_path(id: params[:id])
      else
        flash[:success] = "Тест назначен пользователям"
        redirect_to tests_path
      end
    end
  end

  def edit
    @test = Test.find(params[:id])
    @result = @test.results.find_by(user_id: current_user.id)
    @pass_time = @result.pass_time
    if @result.attempt_count < 1
      flash[:danger] = @result.attempt_count == 0 ? "Закончились попытки" : "Вы уже прошли тест"
      redirect_to tests_path
    end
    @result.attempt_count -= 1 if @result.attempt_count > 0
    @result.save
  end

  def update
    @test = Test.find(params[:test_id])
    @result = @test.results.find_by(user_id: current_user.id)
    @pass_time = params[:passed_time].to_i
    user_id = current_user.id
    test_id = @test.id
    results = results(@test)
    if results.include?(nil)
      flash[:danger] = "Вы ответили не на все вопросы!"
      render 'edit' and nil
    elsif @result.update_attributes(user_id: user_id,
                                    test_id: test_id,
                                    results: results)
      flash[:success] = "Результат принят. Осталось попыток: #{@result.attempt_count}"
      if percent(@test, @result) >= 70
        pass_test_post(current_user, @test, @result)
        @result.attempt_count = -1
        @result.save
      end
      redirect_to result_path(@result)
    else
      flash[:danger] = @result.errors.full_messages.join(".\n")
      redirect_to tests_path
    end
  end

  private

    def pass_test_post(user, test, result)
      link = view_context.link_to("Результат здесь.", result_path(result))
      user.microposts.create!(content: "Мной был пройден тест: \"#{test.name}\". #{link}")
    end

    def right_answer_count(questions, result)
      right_answers_count = 0
      questions.each_with_index do |question, index|
        if question.answers.length == 1
          answer = result.results[index][:answer]
        else
          answer = question.answers[result.results[index].to_i].answer
        end
        right_answer = question.answers[question.right_answer-1].answer
        right_answers_count += 1 if right_answer == answer
      end
      right_answers_count
    end

    def percent(test, result)
      right = right_answer_count(test.questions, result)
      right.to_f*100 / test.questions.length
    end

    def results(test)
      results = []
      test.questions.each_with_index do |question, index|
        if question.answers.length == 1
          result = params[:"#{index}"].blank? ? nil : params[:"#{index}"]
          results[index] = result ? { :answer => result } : nil
        else
          results[index] = params[:"#{index}"] || nil
        end
      end
      results
    end
end

app/helpers/results_helper.rb
module ResultsHelper

  def find_result(test, user)
    user.results.find_by(test_id: test)
  end
end

app/views/results/_questions.html.erb
<% @questions.each_with_index do |question, index| %>
  <% answer = question.answers.length == 1 ? @result.results[index][:answer] : question.answers[@result.results[index].to_i].answer %>
  <% right_answer = question.answers[question.right_answer-1].answer %>
  <% if right_answer == answer %>
    <tr class="bg-success">
  <% else %>
    <tr class="bg-danger">
  <% end %>
      <td><%= "#{index+1}. #{question.question}" %></td>
      <td class="center"><%= answer %></td>
      <td class="center">
        <% if current_user.admin?%>
          <%= right_answer %>
        <% else %>
          <%= right_answer == answer ? "+" : "-" %>
        <% end %>
      </td>
  </tr>
<% end %>
<thead class="thead">
  <th><%= "Итого:" %></th>
  <th class="center"> <%= "ответов: #{@questions.length}" %></th>
  <th class="center"><%= "правильных: #{@right_answers_count}" %></th>
</thead>

app/views/results/edit.html.erb
<% provide(:title, 'Пройти тест') %>
    <h1><%= @test.name %></h1>
    <div class="row">
      <h4>Осталось попыток: <%= @result.attempt_count + 1 %></h4>
      <h4>Осталось времени: <b id="count"></b></h4>
    </div>
<ul class="tests">
  <%= form_for(@result) do |f| %>
    <% @test.questions.each_with_index do |question, index| %>
      <li>
        <table class="table-hover btn-group-vertical col-md-12" data-toggle="buttons">
          <div id="name" <%= "class=bg-danger" if action_name == 'update' && params[:"#{index}"].blank? %>>
            <%= "#{index+1}. " + question.question %>
          </div>
          <% if question.answers.length == 1 %>
            <tr>
              <td>
                <%= text_field_tag index, params[:"#{index}"], class: 'form-control' %>
              </td>
            </tr>
          <% else %>
            <% question.answers.each_with_index do |answer, ans_index| %>
              <tr class="<%= if ans_index.to_s == params[:"#{index}"]
                               "btn col-md-12 radio-label bg-info"
                             else
                               "btn col-md-12 radio-label"
                             end %>">
                <td>
                  <%= radio_button_tag index, ans_index,
                                       ans_index.to_s == params[:"#{index}"] ? true : false %>
                </td>
                <td>&nbsp;&nbsp;</td>
                <td>
                  <%= label_tag answer.answer %>
                </td>
              </tr>
              <tr></tr>
            <% end %>
          <% end %>

        </table>
      </li>
    <% end %>
    <%= hidden_field_tag :test_id, @test.id  %>
    <%= hidden_field_tag :passed_time %>
    <%= f.submit "Ответить", class: "btn btn-primary" %>
  <% end %>
</ul>
<script>
    time = <%= @pass_time %>;
    timer();
</script>

app/views/results/new.html.erb
<% provide(:title, 'Назначить тест') %>
<% provide(:button_text, 'Save changes') %>
<h4>Назначение пользователям теста: <%= @test.name %></h4>
<%= form_for @result do |f| %>
  <table class="row table table-hover">
    <thead class="thead-default">
    <th class="col-md-4"><%= "Пользователь" %></th>
    <th class="col-md-2 center"><%= "Назначить" %></th>
    <th class="col-md-3 center"><%= "Количество попыток" %></th>
    <th class="col-md-3 center"><%= "Время выполнения, мин." %></th>
    </thead>
    <% @users.each do |user|%>
      <% result = find_result(@test, user) %>
      <tr>
        <td>
          <%= gravatar_for user, size: 30 %><%= link_to user.name, user %>
        </td>
        <td>
          <%= check_box_tag "users[#{user.id}]", "checked",result ? true : false%>
        </td>
        <td>
          <%= text_field_tag "attempt_count[#{user.id}]", result ? result.attempt_count : "3", class: "form-control" %>
        </td>
        <td>
          <%= text_field_tag "pass_time[#{user.id}]", result ? result.pass_time/60 : "20", class: "form-control" %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= hidden_field_tag :id, @test.id  %>
  <%= f.submit "Назначить", class: "btn btn-primary col-md-2" %>
<% end %>

app/views/results/show.html.erb
<% provide(:title, "Результат теста: #{@test.name}") %>
<h2><%= "Результат теста: #{@test.name}" %></h2>
<% if @result.results.any? %>
  <table class="row table table-hover table-bordered result-table">
    <thead class="thead-default">
      <th class="col-md-7"><%= "Вопрос" %></th>
      <th class="col-md-2 center"><%= "Ответ" %></th>
      <th class="col-md-3 center"><%= "Правильный ответ" %></th>
    </thead>
    <%= render 'questions' %>
  </table>
  <div class="row">
    <h4><%= "Правильно решено: #{number_to_percentage(@percent, precision: 2)}" %></h4>
    <% if @percent < 70 %>
      <h4><%= "Вы набрали менее 70%. Тест не пройден." %></h4>
      <%= link_to "Попробовать еще раз?", edit_result_path(@test) %>
    <% else %>
      <h4><%= "Тест пройден!" %></h4>
    <% end %>
  </div>
<% end %>