config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  mount TalkingStick::Engine, at: '/talking_stick'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :tests
  resources :questions
  resources :answers,             only: [:create, :destroy]
  resources :results

  post '/talking_stick/rooms/:id', to: 'talking_stick/rooms#img_board'
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    ОНЛАЙН-РЕПЕТИТОР ПО МАТЕМАТИКЕ ДЛЯ УЧЕНИКОВ 5-11 КЛАССОВ
  </small>
  <nav>
    <ul>
      <li><%= link_to "О нас",   about_path %></li>
      <li><%= link_to "Контакты", contact_path %></li>
      <li><a href="http://vk.com/olyavod" target="_blank">ВК</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "onMath.ru", root_path, id: "logo" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to "Пользователи", users_path if current_user.admin?%></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Настройки", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Выйти", logout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Войти", login_path %></li>
          <% end %>
        </ul>
    </div>
  </div>
</header>

app/views/layouts/_left_menu.html.erb
<ul class="nav nav-pills nav-stacked">
  <div class="user_info"><%= render 'shared/user_info' %></div>
  <li class=<%= 'active' if current_page?(root_path) %>><%= link_to "Общение", root_path %>
  <li class=<%= 'active' if current_page?(controller: '/tests') %>><%= link_to "Тесты", tests_path %></li>
  <li><%= link_to "Rooms", talking_stick.rooms_path %>
  </li>
</ul>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all',
                          'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<% if not show_room %>
  <div class="container">
    <div class="row">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <% if logged_in? %>
        <div class="col-md-3">
          <%= render 'layouts/left_menu' %>
        </div>
        <div class="col-md-9">
        <%= yield %>
        </div>
      <% else %>
        <%= yield %>
      <% end %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
<% else %>
  <%= yield %>
<% end %>
</body>
</html>